name: Automação - Simulador de empréstimo online

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Instalar dependências
        run: npm install

      - name: Automatização de testes com Cypress
        run: npm run cypress:open